databricks_resources:
  llm_endpoint_name: databricks-dbrx-instruct
  vector_search_endpoint_name: one-env-shared-endpoint-16
input_example:
  messages:
  - content: Find a candidate with expertise in Power BI and SQL for a data analytics
      project.
    role: user
  - content: Based on the provided context, here are two profiles with SQL and PowerBI
      skills.
    role: assistant
  - content: From the candidates you found, identify if any would be a good fit for
      a lead position.
    role: user
llm_config:
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_prompt_template: 'You are an AI assistant designed to assist in evaluating job
    candidates based on their resumes. Your role is to answer questions about candidates''
    suitability for a job based on the information provided in the resumes. If you
    do not know the answer, say that you do not have enough information to make an
    assessment. Here is some context from the resumes: {context}. Based on this context,
    answer the following question about the candidates: {question}. Provide a direct
    and concise answer. Do not repeat the question, do not start your answer with
    ''The answer to the question is'' or any similar phrases, and do not mention the
    context or the question. Simply provide the information needed.'
  llm_prompt_template_variables:
  - context
  - question
retriever_config:
  chunk_template: 'Passage: {chunk_text}

    '
  data_pipeline_tag: poc
  embedding_model: databricks-gte-large-en
  parameters:
    k: 3
    query_type: ann
  schema:
    chunk_text: content
    document_uri: url
    primary_key: id
  vector_search_index: merve_hackathon.rag_chatbot.databricks_pdf_documentation_self_managed_vs_index
